### ISSUE TITLE
Discord support for community.

### ISSUE THREAD

**Issue by pspatel602** [sc4v3ng3r/flutter_audio_query#45]
It is difficult to ask question in GitHub. So if there is discord community for so we can help each other and learn and grow from it. Many other package authors such as audioplayers and flame etc open discord community. This step is really helpful for all type of developers from beginners to advanced level.   And Thanks for making such an awesome package.

**Comment by sc4v3ng3r** [comment]
Thanks for your suggestion @pspatel602. It's something important and I'll take your advise.
Of course there is the tag ```flutter-audio-query``` in StackOverflow and you can use it in your questions about this package. For sure me or other developers would be able to make the things clear for you and the others.

**Comment by pparh602** [comment]
@sc4v3ng3r Thanks for making such an awesome plugin but brother Could you please provide support for discord server or Telegram group for Flutter-Audio-Query. Because on Stack overflow no one reply. Please check out following question i asked on Stack-overflow 5 months ago: [Question link](https://stackoverflow.com/questions/64426606/how-can-i-use-other-packagefetch-metadata-with-file-picker-to-show-only-select)
And still there is no answer.
